name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies and build
        run: |
          npm ci
          npm run build

      - name: Authenticate with Firebase
        run: |
          npm install -g firebase-tools
          echo $FIREBASE_TOKEN | firebase login:ci

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.1//0gVvSm8O-u375CgYIARAAGBASNwF-L9IrUddwYR-tcFYkvm2Sy74j87CmdKljDkts2UPne6eyCDxwcly4MOhxsQDiAZTaEyRW2Nc }}
